In [13]:
import numpy as np
import pandas as pd

In [14]:
s = pd.Series(np.random.randint(1,1000,size=(1000)))
# s
s.head()
s.tail()
s.head(10)
s.tail(20)

980    896
981    872
982    934
983    633
984    575
985    688
986    633
987    481
988    683
989    459
990    921
991    877
992    898
993     86
994    262
995    523
996    762
997    680
998    833
999    226
dtype: int32

In [15]:
# attributes
df = pd.DataFrame(np.random.randint(1,20,size=(5,4)), index = ['one','two','three','four','five'], columns = ['A','B','C','D'])
df
df.shape # gives dims like ndarray
df[:2]
df.columns = [x.lower() for x in df.columns]
df.columns
df
# to get actual data
s.array
s.index
s.index.array
s.to_numpy()
np.asarray(s)

array([471, 168, 319, 892, 365, 304, 402, 165, 882, 453, 198, 118, 317,
       200, 371, 368, 147,  36, 266, 139, 889, 278, 223, 798,  82, 939,
       404, 381, 673, 768, 336, 779, 330, 469, 917, 248, 943, 675, 948,
       508, 378, 406, 453, 647, 497, 494, 243, 901,  59, 229, 512, 842,
       708, 988, 153,   1, 208, 284,  50, 717, 416, 846, 486, 830, 375,
       682, 441, 542, 409, 119, 892, 646,  93, 745,  64, 732,  49, 952,
       363, 429, 153, 868, 496, 128, 894, 700, 693, 904,  52, 725, 637,
       196, 645, 737, 912, 725, 950,  73, 648, 845, 956, 178, 894, 713,
       582, 749, 483, 900, 364, 452, 558, 228, 664, 279, 927, 291,  54,
       966, 734, 637, 470, 336, 642, 144, 456, 162,  90, 467, 542, 856,
       699, 509, 315, 955, 792, 926, 463, 311, 658, 735, 445, 872, 142,
       113, 813, 625, 569,   1, 268, 957, 728, 183, 231, 988, 604, 500,
       432, 486, 734, 978, 784, 682, 776, 117, 548, 143, 826, 827, 835,
       690, 461, 160, 466, 413, 465, 597, 505, 673, 469, 323, 153, 206,
       975, 993, 735,   7, 794, 419, 974, 277, 986, 173, 594, 261, 831,
       767, 737, 539, 848, 775, 890, 201, 317, 702, 373, 868, 509, 885,
       372, 866, 175, 506, 517, 171, 494, 424,  56, 349, 642, 323, 447,
       119, 495, 590, 680, 238, 932,  22, 123, 526, 713, 524,  89, 490,
       838, 424, 359, 760, 377, 953, 880, 365, 578, 609, 466,  94, 453,
       418, 628, 680, 730, 527, 281,  80, 896,  60, 949, 144, 921, 585,
       864, 173, 812, 737,  50, 234,  38,  85,  63, 588, 410, 951, 751,
       534, 749,  20, 255, 582, 621, 687, 647,  19, 157, 168, 541,  93,
       178, 673, 514,  16, 248, 841, 304, 983, 306, 293, 538, 808, 523,
       826, 288, 683, 434, 464, 340, 713, 521,  70, 678,  89, 228, 770,
       415, 238, 441, 545, 416, 690, 157, 224, 294, 228, 293, 995, 703,
       554, 671,  77, 458, 544, 338, 754, 898, 437, 293, 190, 186, 961,
       585, 347, 627, 465, 637,  94, 116, 759,  78, 941, 611, 384, 330,
       219, 542, 680, 200, 172, 748, 615, 781, 874,  50, 841, 164, 172,
       426, 523,  51, 152, 418, 139, 281, 998, 254, 559, 502,  66, 336,
       680, 402,  21, 817, 519, 574,  89, 578, 743, 727, 840,  28, 240,
       435, 438, 296, 544, 289, 283, 921, 799, 483, 471, 830, 316,  87,
       270, 575, 500, 712, 827, 429, 159, 162, 789,  42, 286, 937, 324,
       571, 159, 454, 694, 599, 159, 756, 616, 799, 106, 315, 823,  52,
        66, 856, 908, 235, 186, 533, 157, 508, 404, 452,  24, 275, 223,
       632, 403, 396, 910, 582, 334, 520, 445, 655,  11, 117, 867, 182,
        33, 845, 995, 790, 919, 534, 599, 176, 397, 690, 415, 855, 574,
       800, 905, 352, 237, 833, 467, 873, 775, 143, 516, 863, 364, 581,
       780, 501, 213, 353, 516, 359, 396, 726, 195, 655, 923, 314, 235,
       676, 709, 584, 351, 932, 711, 739, 789, 660, 451, 694, 504, 785,
       946, 423, 291, 440, 126, 133, 238, 987, 199, 620, 381, 165, 952,
       371,  20, 755, 226, 379, 406,  41, 961, 513, 581,   3, 585,  64,
       132, 382, 731,  38, 942, 789, 827, 284,  11, 682, 666, 133,  57,
        73, 488, 173,  71, 699, 606, 908, 880, 744, 980, 991, 408, 713,
       153,  63, 973, 741,  56, 396, 284,  48, 633, 936, 401, 360, 656,
       546, 104, 986, 891, 970, 146, 657, 973, 821, 386, 738,  66, 186,
        79, 928, 803, 341, 288, 676, 720, 775, 276, 265, 205,  63, 628,
       886, 852, 977, 385, 380, 858, 483,  98, 591, 154, 772, 284, 445,
       314, 602, 453, 509, 417, 343, 400, 547, 673,  89, 229, 588, 219,
       125, 911, 600, 594, 683, 440, 903, 551, 606, 545, 483, 815, 943,
        54, 280, 542, 919, 252, 559, 272, 228,  40, 686, 667, 151, 955,
       380, 694,  23, 595,  49, 886, 171, 940, 640, 904, 443, 750, 493,
       782, 597, 887, 673, 732, 350, 860, 823, 693, 814, 645, 771, 681,
       608, 127, 268, 835,   2, 236, 178, 972, 932, 861, 197, 543, 340,
        80, 147, 862, 849, 598, 804, 688, 315, 854, 460, 957, 901, 211,
        58, 244, 494, 539, 937, 857, 668, 788,  51, 604, 159, 155, 470,
       775, 341, 191, 671, 465, 565, 454, 812, 361, 595, 564, 230, 550,
       244, 129, 181, 387, 925,   7, 122, 782, 882, 306, 800, 393, 899,
       470,   1, 850, 802, 976, 271, 443, 585, 286, 161, 413, 184, 661,
       936, 955, 430, 581, 284, 878, 637, 933, 387, 687, 142, 258, 665,
       360, 379, 474, 138, 395, 208, 893,  98, 808,  84, 441, 208, 915,
       717, 134, 256,  15, 801, 144, 770, 125, 409, 665, 679, 557, 789,
       463,  53, 555, 559, 892,  89, 314,  95, 890, 873, 511,  29, 450,
       663, 590, 201, 812, 604, 654, 664, 591,  24, 200, 786, 722, 675,
       342, 163,  96, 733, 430, 285, 213, 653, 236, 268,  99, 518, 213,
       259, 685, 492, 402,  36, 765, 719, 877, 671, 995, 960, 416, 222,
       455, 597,  97, 981, 787, 963, 147, 382, 428, 928, 597, 781, 347,
       684, 493, 562,  60, 585, 122, 747, 687,  67, 660, 420, 539, 945,
       375, 427,  93, 258, 771, 889, 630, 593, 566, 105, 792, 372, 751,
       386, 919, 494, 518, 551, 918, 744,  95, 404, 852, 707, 415, 533,
        82, 761, 607, 204, 984, 618, 700, 622, 142, 484, 842, 598, 202,
       419, 972, 919, 478, 598, 425, 124, 377, 378, 579, 504, 587, 150,
       685,  15, 526,  80, 706, 245, 671, 469, 681, 849, 612,  98, 672,
        85,  86, 795, 280, 839, 951, 420, 711, 386, 621, 830, 638, 456,
       448, 132, 315, 796, 560, 859, 148, 964, 304, 627, 267,  91, 250,
       149, 421, 963, 260, 913, 734, 800, 407, 417, 874, 399, 618, 307,
       816, 636, 121, 257, 162, 896, 872, 934, 633, 575, 688, 633, 481,
       683, 459, 921, 877, 898,  86, 262, 523, 762, 680, 833, 226],
      dtype=int32)

In [21]:
df = pd.DataFrame({
    'one': pd.Series(np.random.randint(1,3, size=(3)), index = ['a','b','c']),
    'two': pd.Series(np.random.randint(2,4, size = (4)), index = ['a','b','c','d']),
    'three': pd.Series(np.random.randint(3,7,size=(3)), index = ['b','c','d'])
})
df
row = df.iloc[1]
column = df['two']
df.sub(row,axis = 'columns')
df.sub(row,axis=1)
df.sub(column, axis='index')
df.sub(column,axis=0)

   one  two  three
a -2.0    0    NaN
b  0.0    0    1.0
c  0.0    0    4.0
d  NaN    0    0.0

In [27]:
dfmi = df.copy()
dfmi.index = pd.MultiIndex.from_tuples(
    [(1,'a'),(1,'b'),(1,'c'),(2,'a')], name = ['first','second']
)
dfmi
dfmi.sub(column,axis=0,level='second')

              one  two  three
first second
1     a      -2.0    0    NaN
      b       0.0    0    1.0
      c       0.0    0    4.0
2     a       NaN    0    0.0