In [54]:
import pandas as pd
import numpy as np

In [ ]:
# ====SERIES====
# from nd array
s = pd.Series(np.random.randn(5),index = ['A','B','C','D','E'], name="Learning Series")
s
# s.index
# pd.Series(np.random.randn(5))
# pd.Series([1,2,3,4,5])
# pd.Series(1,2,3,4,5) ------ error

A   -0.544495
B    0.333259
C   -0.174532
D   -0.260928
E    0.969264
Name: Learning Series, dtype: float64

In [56]:
# from dict
dictionary = {'b':1, 'a':2, 'c':0}
d = pd.Series(dictionary)
# d
pd.Series(dictionary,index = ['a','b','c','d','e'])

a    2.0
b    1.0
c    0.0
d    NaN
e    NaN
dtype: float64

In [57]:
# from dict
dictionary = {'b':1, 'b':2, 'c':0} # overwrite
d = pd.Series(dictionary)
d

b    2
c    0
dtype: int64

In [58]:
# from scalar value
pd.Series(5,index = ['a','b','c','d','e'])

s.iloc[0]
s.iloc[:3]
s[s > s.median()]
s.iloc[[1,2,4]]
np.exp(s) # e^x
s.array
s.to_numpy()
'E' in s
'F' in s
# s['f'] ----- exception raised
s.get('f') # ---- no exception raised
s.get('f',np.nan)

nan

In [ ]:
# vectorised ops and label alignment
s + s
s*2
np.exp(s)
s.iloc[1:] + s.iloc[:-1]
s.name
s=s.rename("Learned Series")
s**5

A   -0.047860
B    0.004111
C   -0.000162
D   -0.001209
E    0.855483
Name: Learned Series, dtype: float64

:

In [ ]:
# ====DATA FRAME====
# from dict of series
d = {
    'one': pd.Series([1,2,3.0], index = ['a','b','c']),
    'two': pd.Series([4.0,5,6,1], index = ['a','b','c','d'])
}
df = pd.DataFrame(d)
df
pd.DataFrame(d,index = ['b','d','a'])
pd.DataFrame(d,index=['a','b','e'],columns = ['two','three'])
# df.index
# df.columns

   two three
a  4.0   NaN
b  5.0   NaN
e  NaN   NaN

In [79]:
# dict of ndarrays/lists
d = {
    'one': [1,2,3,4], # arrays length different = ValueError
    'two': [2,3,4,5]
}
pd.DataFrame(d)
pd.DataFrame(d, index = ['a','b','c','d']) # index length not same = ValueError

   one  two
a    1    2
b    2    3
c    3    4
d    4    5